### ISSUE TITLE
Try to parse object as JSON if object if of type string

### ISSUE THREAD

**Issue by Bartozzz** [Bartozzz/json-overrides#41]
Right now, `overrides` accepts a plain object as input, so:

```javascript
override({
  a: 1,

  overrides: {
    foo: {
      a: 2
    }
  }
}, "foo");
```
…will return:

```json
{
  "a": 2
}
```

It would be nice if we could pass serialized objects (pure JSON strings) as argument, so something like this would be possible:

```javascript
overrides(
  JSON.stringify({
    a: 1,
    overrides: {
      foo: {
        a: 2
      }
    }
  }),
  "foo"
);
```

It has plenty of use cases, ex when reading directly from a file (`package.json`, etc.).

**Comment by mathagician** [comment]
@Bartozzz I would like to work on this issue. Could you please explain in detail.

How to reproduce this issue.

**Comment by Bartozzz** [comment]
Hey @mathagician. I've updated the initial comment with more details. Also, this is a feature request – not an issue.
